// TEMPLATE: one entry per card. Add a card by copying one block.
// category: used for the filter tabs. cta: the text at the bottom of the card.
export const cards = [
  {
    category: 'Programs',
    href: '/design-system/program.html',
    cover: '/portfolio/work/images/cover/Cover - Go1 Content Curation.png',
    coverAlt: 'Describe the image',
    badge: 'Open for enrolment',
    meta: '12 sessions · Weekly',
    title: 'Program card title',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'View program',
    newTab: false,
  },
  {
    category: 'Events',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: '12 Dec 2026',
    meta: 'Online · 90 min',
    title: 'Event card title',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'Save my seat',
    newTab: false,
  },
  {
    category: 'Learning',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Refer Plus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Lesson · 10 min read',
    title: 'Learning card title',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'Start learning',
    newTab: false,
  },
  {
    category: 'Programs',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Short detail',
    title: 'Card number 4',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'View program',
    newTab: false,
  },
  {
    category: 'Events',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Short detail',
    title: 'Card number 5',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'Save my seat',
    newTab: false,
  },
  {
    category: 'Learning',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Short detail',
    title: 'Card number 6',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'Start learning',
    newTab: false,
  },
  {
    category: 'Learning',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Short detail',
    title: 'Card number 7',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'Start learning',
    newTab: false,
  },
  {
    category: 'Programs',
    href: '/design-system/resource.html',
    cover: '/portfolio/work/images/cover/Cover - Pinbus.png',
    coverAlt: 'Describe the image',
    badge: null,
    meta: 'Short detail',
    title: 'Card number 8',
    description: 'One or two sentences that tell people what this is and why it matters.',
    cta: 'View program',
    newTab: false,
  },
]

// Which layout opens first: 'cards' (with image) or 'compact' (no image, more per row).
// Visitors can switch with the buttons above the list.
export const defaultView = 'cards'
